"""adding search query

Revision ID: 02fd820ef1a9
Revises: 9c4d2b1f7a66
Create Date: 2026-03-20 14:23:07.988154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02fd820ef1a9'
down_revision: Union[str, Sequence[str], None] = '9c4d2b1f7a66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommended_places', sa.Column('query_to_search', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommended_places', 'query_to_search')
    # ### end Alembic commands ###
