"""test

Revision ID: 1883f4b07d98
Revises: 7085a51c7ed4
Create Date: 2026-02-27 20:38:40.203009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1883f4b07d98'
down_revision: Union[str, Sequence[str], None] = '7085a51c7ed4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip_vacancies', sa.Column('people_joined', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trip_vacancies', 'people_joined')
    # ### end Alembic commands ###
