"""adding travel style

Revision ID: b4f77f403b3c
Revises: ad4ec6be5861
Create Date: 2026-02-26 13:58:24.609113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4f77f403b3c'
down_revision: Union[str, Sequence[str], None] = 'ad4ec6be5861'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('travel_styles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_travel_styles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('travel_style_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['travel_style_id'], ['travel_styles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'travel_style_id', name='unique_user_travel_style')
    )
    op.create_index('idx_profile_travel_styles', 'user_travel_styles', ['profile_id'], unique=False)
    op.create_index('idx_travel_style_profiles', 'user_travel_styles', ['travel_style_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_travel_style_profiles', table_name='user_travel_styles')
    op.drop_index('idx_profile_travel_styles', table_name='user_travel_styles')
    op.drop_table('user_travel_styles')
    op.drop_table('travel_styles')
    # ### end Alembic commands ###
